package lista06.exercicio03;

public class Exercicio03 extends javax.swing.JFrame {

    /**
     * Creates new form Exercicio03
     */
    public Exercicio03() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_principal = new javax.swing.JLabel();
        lbl_valor = new javax.swing.JLabel();
        tf_valor = new javax.swing.JTextField();
        jComboBox_moeda = new javax.swing.JComboBox<>();
        lbl_moeda = new javax.swing.JLabel();
        lbl_conversao = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Conversor");

        lbl_principal.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lbl_principal.setText("Conversor Monetário");

        lbl_valor.setText("Valor em Reais (R$):");

        tf_valor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tf_valorKeyReleased(evt);
            }
        });

        jComboBox_moeda.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dólar", "Euro", "Libra", "Peso Argentino" }));
        jComboBox_moeda.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox_moedaItemStateChanged(evt);
            }
        });

        lbl_moeda.setText("Moeda referência:");

        lbl_conversao.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lbl_conversao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_conversao.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lbl_principal)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_valor)
                        .addGap(12, 12, 12)
                        .addComponent(tf_valor, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_moeda)
                        .addGap(12, 12, 12)
                        .addComponent(jComboBox_moeda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lbl_conversao, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(90, 90, 90))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_principal)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_valor)
                    .addComponent(tf_valor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox_moeda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_moeda))
                .addGap(18, 18, 18)
                .addComponent(lbl_conversao, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tf_valorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_valorKeyReleased
        funcaoConversao();
    }//GEN-LAST:event_tf_valorKeyReleased

    private void jComboBox_moedaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox_moedaItemStateChanged
        funcaoConversao();
    }//GEN-LAST:event_jComboBox_moedaItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Exercicio03.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Exercicio03.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Exercicio03.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Exercicio03.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Exercicio03().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox_moeda;
    private javax.swing.JLabel lbl_conversao;
    private javax.swing.JLabel lbl_moeda;
    private javax.swing.JLabel lbl_principal;
    private javax.swing.JLabel lbl_valor;
    private javax.swing.JTextField tf_valor;
    // End of variables declaration//GEN-END:variables

    private void funcaoConversao() {
        double s = Double.valueOf(tf_valor.getText());
        String conversao = "";
        double cotacao = 0;
        if (!tf_valor.getText().equals("")) {
            String moeda = jComboBox_moeda.getSelectedItem().toString();
            switch (moeda) {
                case "Dólar": {
                    cotacao = s / 4.30;
                    conversao = String.format("US$%.2f", cotacao);
                    break;
                }
                case "Euro": {
                    cotacao = s / 4.86;
                    conversao = String.format("€$%.2f", cotacao);
                    break;
                }
                case "Libra": {
                    cotacao = s / 5.43;
                    conversao = String.format("£$%.2f", cotacao);
                    break;
                }
                case "Peso Argentino": {
                    cotacao = s / 0.11;
                    conversao = String.format("$%.2f", cotacao);
                    break;
                }
            }
            lbl_conversao.setText(conversao);
        } else {
            lbl_conversao.setText("");
        }
    }
    
}
