package lista07.exercicio03;

import javax.swing.JOptionPane;

public class Exercicio03 extends javax.swing.JFrame {

    /**
     * Creates new form Exercicio03
     */
    public Exercicio03() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_nome = new javax.swing.JLabel();
        tf_nome = new javax.swing.JTextField();
        lbl_salario = new javax.swing.JLabel();
        tf_salario = new javax.swing.JTextField();
        lbl_cargo = new javax.swing.JLabel();
        jComboBox_cargo = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        lbl_reajuste = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_reajuste = new javax.swing.JTable();
        btn_reajuste = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Reajuste do Salário");
        setResizable(false);

        lbl_nome.setText("Nome:");

        lbl_salario.setText("Salário (R$):");

        lbl_cargo.setText("Cargo:");

        jComboBox_cargo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Presidente", "Diretor", "Gerente", "Engenheiro", "Pesquisador", "Secretário" }));

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lbl_reajuste.setText("Tabela de Reajuste");

        tbl_reajuste.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Presidente", "15%"},
                {"Diretor", "12%"},
                {"Gerente", "9%"},
                {"Engenheiro", "7.5%"},
                {"Pesquisador", "5.9%"},
                {"Secretário", "8%"}
            },
            new String [] {
                "Cargo", "Reajuste"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_reajuste.setEnabled(false);
        jScrollPane1.setViewportView(tbl_reajuste);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(lbl_reajuste)
                .addContainerGap(78, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_reajuste)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                .addContainerGap())
        );

        btn_reajuste.setText("Reajustar");
        btn_reajuste.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_reajusteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_salario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_salario, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(lbl_cargo)
                        .addGap(6, 6, 6)
                        .addComponent(jComboBox_cargo, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_nome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_nome)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79))
            .addGroup(layout.createSequentialGroup()
                .addGap(174, 174, 174)
                .addComponent(btn_reajuste)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_nome)
                    .addComponent(tf_nome, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_salario)
                    .addComponent(tf_salario, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_cargo)
                    .addComponent(jComboBox_cargo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_reajuste)
                .addContainerGap())
        );

        tf_nome.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_reajusteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_reajusteActionPerformed
        double salario, novoSalario = 0;
        String nome, mensagem, cargo;
        if (!tf_nome.getText().equals("") || !tf_salario.getText().equals("")) {
            try {
                nome = tf_nome.getText();
                salario = Double.valueOf(tf_salario.getText());
                cargo = jComboBox_cargo.getSelectedItem().toString();
                switch (cargo) {
                    case "Presidente": {
                        novoSalario = salario + salario * 0.15;
                        break;
                    }
                    case "Diretor": {
                        novoSalario = salario + salario * 0.12;
                        break;
                    }
                    case "Gerente": {
                        novoSalario = salario + salario * 0.09;
                        break;
                    }
                    case "Engenheiro": {
                        novoSalario = salario + salario * 0.075;
                        break;
                    }
                    case "Pesquisador": {
                        novoSalario = salario + salario * 0.059;
                        break;
                    }
                    case "Secretário": {
                        novoSalario = salario + salario * 0.08;
                        break;
                    }
                }
                if (novoSalario > 1000) {
                    JOptionPane.showMessageDialog(null, "Salário acima do permitido!", "Erro", JOptionPane.WARNING_MESSAGE);
                } else {
                    mensagem = String.format("Nome: %s\nCargo: %s\nSalário Antigo: R$%.2f\nSalário Reajustado: R$%.2f", nome, cargo, salario, novoSalario);
                    JOptionPane.showMessageDialog(null, mensagem, "Informações", JOptionPane.INFORMATION_MESSAGE);
                }
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(null, "Salário inválido, tente novamente...", "Erro", JOptionPane.WARNING_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Nenhum campo pode estar vazio", "Erro", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btn_reajusteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Exercicio03.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Exercicio03.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Exercicio03.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Exercicio03.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Exercicio03().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_reajuste;
    private javax.swing.JComboBox<String> jComboBox_cargo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_cargo;
    private javax.swing.JLabel lbl_nome;
    private javax.swing.JLabel lbl_reajuste;
    private javax.swing.JLabel lbl_salario;
    private javax.swing.JTable tbl_reajuste;
    private javax.swing.JTextField tf_nome;
    private javax.swing.JTextField tf_salario;
    // End of variables declaration//GEN-END:variables

}
